/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.AdminBUS;
import static GUI.MainFrameGUI.txDonGia3;
import static GUI.MainFrameGUI.txHoLotTacGia;
import static GUI.MainFrameGUI.txLoaiSach1;
import static GUI.MainFrameGUI.txNgayXuatBan1;
import static GUI.MainFrameGUI.txNhaXuatBan1;
import static GUI.MainFrameGUI.txTenSach4;
import static GUI.MainFrameGUI.txTenTacGia;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ha
 */
public class HoTroNhapThongTinSachGUI extends javax.swing.JFrame {

    public HoTroNhapThongTinSachGUI() {
        initComponents();

        try {
            AdminBUS adminBus = new AdminBUS();
            tbQuanLySanPham.setModel(adminBus.hienThiHoTro());
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSachDaNhap = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbQuanLySanPham = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column) {
                return false;
            }
        };
        jLabel11 = new javax.swing.JLabel();
        cbTimKiem2 = new javax.swing.JComboBox<>();
        txTimKiem2 = new javax.swing.JTextField();
        btnTimkiem1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbLoaiSach1 = new javax.swing.JComboBox<>();
        btnTimkiem2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        lbSachDaNhap.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbSachDaNhap.setForeground(new java.awt.Color(255, 255, 255));
        lbSachDaNhap.setText("Sách đã nhập");

        tbQuanLySanPham.getTableHeader().setFont(new Font("Arial",Font.PLAIN,14));
        tbQuanLySanPham.setBackground(new java.awt.Color(204, 204, 255));
        tbQuanLySanPham.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbQuanLySanPham.setForeground(new java.awt.Color(51, 0, 51));
        tbQuanLySanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Họ lót tác giả", "Tên tác giả", "Loại sách", "Ngày xuất bản", "Nhà xuất bản", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbQuanLySanPham.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tbQuanLySanPham.getTableHeader().setReorderingAllowed(false);
        tbQuanLySanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuanLySanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbQuanLySanPham);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tìm kiếm :");

        cbTimKiem2.setBackground(new java.awt.Color(204, 204, 255));
        cbTimKiem2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cbTimKiem2.setForeground(new java.awt.Color(0, 0, 0));
        cbTimKiem2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên sách", "Họ lót tác giả", "Tên tác giả", "Loại sách" }));
        cbTimKiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTimKiem2ActionPerformed(evt);
            }
        });

        txTimKiem2.setBackground(new java.awt.Color(204, 204, 255));
        txTimKiem2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txTimKiem2.setForeground(new java.awt.Color(0, 0, 0));
        txTimKiem2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTimKiem2KeyPressed(evt);
            }
        });

        btnTimkiem1.setBackground(new java.awt.Color(204, 204, 255));
        btnTimkiem1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnTimkiem1.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem1.setText("Tìm kiếm");
        btnTimkiem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiem1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Loại sách :");

        cbLoaiSach1.setBackground(new java.awt.Color(204, 204, 255));
        cbLoaiSach1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cbLoaiSach1.setForeground(new java.awt.Color(0, 0, 0));
        cbLoaiSach1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Tiểu thuyết", "Giáo trình", "Kĩ năng sống", "Văn học", "Tâm lí" }));
        cbLoaiSach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiSach1ActionPerformed(evt);
            }
        });

        btnTimkiem2.setBackground(new java.awt.Color(204, 204, 255));
        btnTimkiem2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnTimkiem2.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem2.setText("Chọn");
        btnTimkiem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiem2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSachDaNhap)
                .addGap(240, 240, 240))
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTimkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLoaiSach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(cbTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(btnTimkiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbSachDaNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimkiem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbLoaiSach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem2))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbQuanLySanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuanLySanPhamMouseClicked

    }//GEN-LAST:event_tbQuanLySanPhamMouseClicked

    private void cbTimKiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTimKiem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTimKiem2ActionPerformed

    private void txTimKiem2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTimKiem2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                timKiemHoTro(cbTimKiem2, tbQuanLySanPham, txTimKiem2);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(HoTroNhapThongTinSachGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txTimKiem2KeyPressed

    private void btnTimkiem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiem1MouseClicked

        try {
            timKiemHoTro(cbTimKiem2, tbQuanLySanPham, txTimKiem2);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(HoTroNhapThongTinSachGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTimkiem1MouseClicked

    private void cbLoaiSach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiSach1ActionPerformed
        AdminBUS adminBus = new AdminBUS();
        adminBus.hienThiLoaiSachHoTro(tbQuanLySanPham, cbLoaiSach1);
    }//GEN-LAST:event_cbLoaiSach1ActionPerformed

    private void btnTimkiem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiem2MouseClicked
        int row = tbQuanLySanPham.getSelectedRow();
        
        if (row >= 0) {

            txTenSach4.setText((String) tbQuanLySanPham.getModel().getValueAt(row, 1));
            txLoaiSach1.setText((String) tbQuanLySanPham.getModel().getValueAt(row, 4));
            txHoLotTacGia.setText((String) tbQuanLySanPham.getModel().getValueAt(row, 2));
            txTenTacGia.setText((String) tbQuanLySanPham.getModel().getValueAt(row, 3));
            txNhaXuatBan1.setText((String) tbQuanLySanPham.getModel().getValueAt(row, 6));
            txNgayXuatBan1.setText((String) tbQuanLySanPham.getModel().getValueAt(row, 5));
            dispose();

        } else
            JOptionPane.showMessageDialog(null, "Bạn hãy chọn 1 dòng trước");
    }//GEN-LAST:event_btnTimkiem2MouseClicked

    private void timKiemHoTro(JComboBox comboBox, JTable table, JTextField textField) throws SQLException {
        AdminBUS adminBus = new AdminBUS();
        adminBus.timKiemHoTro(comboBox, table, textField);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimkiem1;
    private javax.swing.JButton btnTimkiem2;
    private javax.swing.JComboBox<String> cbLoaiSach1;
    private javax.swing.JComboBox<String> cbTimKiem2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbSachDaNhap;
    private javax.swing.JTable tbQuanLySanPham;
    private javax.swing.JTextField txTimKiem2;
    // End of variables declaration//GEN-END:variables
}
