/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LoaiSachBUS;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import static GUI.MainFrameGUI.txLoaiSach1;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ha
 */
public class HoTroNhapLoaiSachGUI extends javax.swing.JFrame {

    /**
     * Creates new form HoTroNhapLoaiSach
     */
    public HoTroNhapLoaiSachGUI() {
        initComponents();

        try {
            LoaiSachBUS loaiSachBus = new LoaiSachBUS();
            loaiSachBus.docDuLieuLoaiSach();
            tbLoaiSach.setModel(loaiSachBus.hienThiLoaiSach());

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbSachDaNhap2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbLoaiSach = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column) {
                return false;
            }
        };
        btnTimkiem6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        lbSachDaNhap2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbSachDaNhap2.setForeground(new java.awt.Color(255, 255, 255));
        lbSachDaNhap2.setText("Loại sách");

        tbLoaiSach.getTableHeader().setFont(new Font("Arial",Font.PLAIN,14));
        tbLoaiSach.setBackground(new java.awt.Color(204, 204, 255));
        tbLoaiSach.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbLoaiSach.setForeground(new java.awt.Color(51, 0, 51));
        tbLoaiSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ));
        tbLoaiSach.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tbLoaiSach.setShowHorizontalLines(true);
        tbLoaiSach.setShowVerticalLines(true);
        tbLoaiSach.getTableHeader().setReorderingAllowed(false);
        tbLoaiSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLoaiSachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbLoaiSach);

        btnTimkiem6.setBackground(new java.awt.Color(204, 204, 255));
        btnTimkiem6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnTimkiem6.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem6.setText("Chọn");
        btnTimkiem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiem6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(lbSachDaNhap2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimkiem6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbSachDaNhap2)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTimkiem6)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLoaiSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiSachMouseClicked

    }//GEN-LAST:event_tbLoaiSachMouseClicked

    private void btnTimkiem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiem6MouseClicked
        int row = tbLoaiSach.getSelectedRow();

        if (row >= 0) {
            txLoaiSach1.setText((String) tbLoaiSach.getModel().getValueAt(row, 1));
            dispose();

        } else
            JOptionPane.showMessageDialog(null, "Bạn hãy chọn 1 dòng trước");
    }//GEN-LAST:event_btnTimkiem6MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimkiem6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbSachDaNhap2;
    private javax.swing.JTable tbLoaiSach;
    // End of variables declaration//GEN-END:variables
}
