/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NhaXuatBanBUS;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static GUI.MainFrameGUI.txNhaXuatBan1;

/**
 *
 * @author Ha
 */
public class HoTroNhapNhaXuatBanGUI extends javax.swing.JFrame {

    /**
     * Creates new form HoTroNhapNhaXuatBanGUI
     */
    public HoTroNhapNhaXuatBanGUI() {
        initComponents();
        
        try {
            NhaXuatBanBUS nhaXuatBanBUS=new NhaXuatBanBUS();
            
            nhaXuatBanBUS.docDuLieuNhaXuatBan();
            tbNhaXuatBan.setModel(nhaXuatBanBUS.hienThiNhaXuatBan());
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbSachDaNhap3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbNhaXuatBan = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column) {
                return false;
            }
        };
        btnTimkiem6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        lbSachDaNhap3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbSachDaNhap3.setForeground(new java.awt.Color(255, 255, 255));
        lbSachDaNhap3.setText("Nhà xuất bản");

        tbNhaXuatBan.getTableHeader().setFont(new Font("Arial",Font.PLAIN,14));
        tbNhaXuatBan.setBackground(new java.awt.Color(204, 204, 255));
        tbNhaXuatBan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbNhaXuatBan.setForeground(new java.awt.Color(51, 0, 51));
        tbNhaXuatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhà xuất bản", "Tên nhà xuất bản"
            }
        ));
        tbNhaXuatBan.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tbNhaXuatBan.setShowHorizontalLines(true);
        tbNhaXuatBan.setShowVerticalLines(true);
        tbNhaXuatBan.getTableHeader().setReorderingAllowed(false);
        tbNhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhaXuatBanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbNhaXuatBan);

        btnTimkiem6.setBackground(new java.awt.Color(204, 204, 255));
        btnTimkiem6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnTimkiem6.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem6.setText("Chọn");
        btnTimkiem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiem6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTimkiem6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbSachDaNhap3)
                        .addGap(244, 244, 244))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbSachDaNhap3)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTimkiem6)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNhaXuatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhaXuatBanMouseClicked

    }//GEN-LAST:event_tbNhaXuatBanMouseClicked

    private void btnTimkiem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiem6MouseClicked
        int row = tbNhaXuatBan.getSelectedRow();

        if (row >= 0) {
            txNhaXuatBan1.setText((String) tbNhaXuatBan.getModel().getValueAt(row, 1));
            dispose();

        } else
            JOptionPane.showMessageDialog(null, "Bạn hãy chọn 1 dòng trước");
    }//GEN-LAST:event_btnTimkiem6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoTroNhapNhaXuatBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoTroNhapNhaXuatBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoTroNhapNhaXuatBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoTroNhapNhaXuatBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoTroNhapNhaXuatBanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimkiem6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbSachDaNhap3;
    private javax.swing.JTable tbNhaXuatBan;
    // End of variables declaration//GEN-END:variables
}
